---
title: "data_manipulation"
author: "Casandra Laney"
date: "2025-09-18"
output: github_document
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
```

Let's import the datasets.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", ".", ""))

litters_df =
  janitor::clean_names(litters_df)

pups_df = 
  read_csv("data/FAS_pups.csv", na = c("NA", ".", ""))

pups_df =
  janitor::clean_names(pups_df)
```

## 'select'

'select' selects variables from my dataframe

select specific variables

```{r}
select(litters_df, group, litter_number, gd0_weight)
```

select a range

```{r}
select(litters_df, group:gd_of_birth)
```

select by removal

```{r}
select(litters_df, group, -group)
select(litters_df, -(group:gd_of_birth))
```

select by prefix

```{r}
select(litters_df, group, starts_with("gd"))
```

rearrange by selecting

```{r echo=TRUE}
select(litters_df, starts_with("gd"), group)
select(litters_df, litter_number, everything())
```

rename by selecting

```{r}
select(litters_df, GROUP = group, everything())
rename(litters_df, GROUP = group)
```

what if i only select one variable...?

```{r}
select(litters_df, group)


pull(litters_df, group)
```

